# Generated by Django 3.2.23 on 2023-11-15 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecttask', '0003_remove_task_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='published_date',
        ),
    ]
