# Generated by Django 3.2.23 on 2023-11-15 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comentapp', '0002_auto_20231115_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='published_date',
        ),
    ]
